# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAposta', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='aposta',
            name='concurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aposta.Concurso'),
        ),
        migrations.AddField(
            model_name='aposta',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aposta.Conta'),
        ),
    ]
