# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aposta', '0004_auto_20170415_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aposta',
            name='concurso',
        ),
        migrations.AddField(
            model_name='aposta',
            name='numConta',
            field=models.IntegerField(null=True),
        ),
    ]
