# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aposta', '0005_auto_20170420_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='email',
            field=models.EmailField(default=0, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conta',
            name='nomeUtilizador',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
