# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aposta', '0006_auto_20170420_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aposta2',
            name='Concurso2_identificao',
        ),
        migrations.AddField(
            model_name='concurso',
            name='dataConcurso',
            field=models.DateTimeField(default=0, verbose_name='dataconcurso'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Aposta2',
        ),
        migrations.DeleteModel(
            name='Concurso2',
        ),
    ]
