# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aposta', '0008_concurso2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Concurso2',
        ),
    ]
