# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='NIF',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='codigopostal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='contacto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='localidade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='morada',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='pais',
            field=models.CharField(max_length=50),
        ),
    ]
